### ISSUE TITLE
HTML5 games preview gives a 404 error on Linux

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#212]
HTML5 games preview gives a 404 error on Fedora 23. Seems like a permission problem.

**Comment by 4ian** [comment]
Strange, the preview are supposed to be created in a temporary directory returned by wxWidgets ? :open_mouth:

**Comment by brylie** [comment]
This also happens on Ubuntu 15.10.

**Comment by brylie** [comment]
When trying to launch the *Platformer* HTML5 example, I have the following error(s) in my console:

```sh
Copying all ressources to /tmp/GDTemporaries/JSPreview/Could not copy include file PlatformBehavior/PlatformerObjectBehavior.h (File not found).
Warning: Unable to found /tmp/GDTemporaries/JSPreview//PlatformBehavior/PlatformerObjectBehavior.h.
```

**Comment by 4ian** [comment]
These warning are not harmful here, the problem is somewhere else.. Maybe GD was unable to launch the internal web server? Could you copy-paste the full content displayed in the terminal (starting from when you launch gdevelop until you launch the preview and get the 404)

**Comment by victorlevasseur** [comment]
If the webserver wasn't started, we wouldn't get a 404.

Le dim. 27 déc. 2015 à 14:08, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment]
Mmm yes very true. In this case, maybe the webserver can't access to the files (permission problem?).

**Comment by brylie** [comment]
Here is a longer error message that I get when running GDevelop as a non-privileged user:

```
Bool attribute "folderProject" not found, returning 0Copying all ressources to /home/brylie/GDevelop projects/My project 11ImageManager: Loading p1_stand.png.ImageManager: Loading p1_jump.png.ImageManager: Loading p1_walk03.png.ImageManager: Loading p1_walk04.png.ImageManager: Loading p1_walk05.png.ImageManager: Loading p1_walk06.png.ImageManager: Loading p1_walk07.png.ImageManager: Loading brickWall.png.ImageManager: Loading grass.png.ImageManager: Loading bridgeLogs.png.ImageManager: Loading grassHalfMid.png.ImageManager: Loading castleCenter.png.ImageManager: Loading bridge.png.ImageManager: Loading Left.png.ImageManager: Loading Right.png.ImageManager: Loading ladder_mid.png.ImageManager: Loading PlayerArea.png.ImageManager: Loading slimeWalk1.png.ImageManager: Loading slimeWalk2.png.ImageManager: Loading slimeDead.png.ImageManager: Loading flyFly1.png.ImageManager: Loading flyFly2.png.ImageManager: Loading flyDead.png.ImageManager: Loading cloud1.png.ImageManager: Loading cloud2.png.ImageManager: Loading cloud3.png.ImageManager: Loading bush.png.ImageManager: Loading cactus.png.ImageManager: Loading plant.png.ImageManager: Loading coinGold.png.ImageManager: Loading shadedDark05.png.ImageManager: Loading shadedDark06.png.ImageManager: Loading shadedDark45.png.ImageManager: Loading shadedDark09.png.Copying all ressources to /tmp/GDTemporaries/JSPreview/Could not copy include file PlatformBehavior/PlatformerObjectBehavior.h (File not found).
Warning: Unable to found /tmp/GDTemporaries/JSPreview//PlatformBehavior/PlatformerObjectBehavior.h.
```

**Comment by 4ian** [comment]
Ok nothing bad here. I'll check by myself on Ubuntu 15.10

**Comment by brylie** [comment]
OK, the following warning looks suspicious:

```
Warning: Unable to found /tmp/GDTemporaries/JSPreview//PlatformBehavior/PlatformerObjectBehavior.h.
```

Notice the double forward slashes after JSPreview.

**Comment by brylie** [comment]
Also, the line directly above the previous warning seems to point to the same problem:

```
Could not copy include file PlatformBehavior/PlatformerObjectBehavior.h (File not found).
```

The *File not found* message matches the text on the 404 screen:

```
Error 404: Not Found
File not found
```

**Comment by 4ian** [comment]
No no, I'm 100% sure it's not related. The 404 is because the webserver did not properly serve the game files. The `Could not copy (File not found)` is a warning because I forgot to remove a file from a list of files that must be copied. This is not related at all :)

**Comment by brylie** [comment]
Alright. Is there some other way I can access error log? E.g. enabling --debug flag, or viewing an error.log file?

**Comment by victorlevasseur** [comment]
@4ian Did you manage to reproduce the issue in a VM ? (I'm having the same problem in Fedora 23 but I don't how the webserver works at all)

**Comment by 4ian** [comment]
Can reproduce the issue. I've pushed a potential fix in this branch: https://github.com/4ian/GD/tree/feature/civetweb-http-server

I've updated the embedded http server by switching from mongoose to civetweb (fork of mongoose, as mongoose isn't MIT anymore, and the API has changed it seems). I've tested that it is still working ok on OS X, must check if things are better now in Ubuntu 15.10

**Comment by 4ian** [comment]
@victorlevasseur Can you try this branch with Fedora 23?

**Comment by victorlevasseur** [comment]
It's already in progress ;)

**Comment by victorlevasseur** [comment]
It's still not working (404 error, exact same error message).

**Comment by 4ian** [comment]
:( I saw an issue on mongoose about 404 when the folder being served was containing non ASCII characters, that why I tried to update it. But anyway the folder shouldn't even contain non ASCII characters as it is something like `/tmp/GDTemporaries/JSPreview`.

**Comment by brylie** [comment]
What about spaces? The default path names for projects contain spaces, which need special treatment on *nix.

**Comment by 4ian** [comment]
Mmm I don't think so, the server is serving the files that have been copied and stored in `/tmp/GDTemporaries/JSPreview` (so no spaces, no special characters :/). And I've checked, the files are properly copied.

**Comment by brylie** [comment]
@4ian have you reproduced this in a Linux OS?

**Comment by 4ian** [comment]
Yep I have reproduced it on Ubuntu 15.10

**Comment by 4ian** [comment]
Found how to fix it! At this line https://github.com/4ian/GD/blob/master/GDJS/GDJS/IDE/HttpServer.cpp#L18
`indexDirectory.ToLocale().c_str()` should be replaced by `indexDirectory.c_str()`.

@victorlevasseur Could you check this? :) Does it make sense to remove the ToLocale() here?
If it's ok I'll release a new version with this fix.

**Comment by victorlevasseur** [comment]
It does not make sense. However, it helped me to spot the issue : ```indexDirectory.ToLocale()``` is a local expression and the returned ```std::string``` is deleted just after this line. So, ```c_str()``` points an invalid characters sequences when ```mg_start``` is called (as it needs it from its ```options``` array). This code is not safe but worked with the old API/ABI of the libstdc++. It's not the case anymore with the brand new libstdc++ ABI (as ```c_str()``` changed its behavior) provided by recent OSes. 

The fix consists of creating a ```std::string``` inside ```HTTPServer::run``` and giving it ```indexDirectory.ToLocale()```. Then, ```c_str()``` is safe until the end of the method.

I'm sending directly the commit on your branch...

**Comment by 4ian** [comment]
Ok make sense now! I guess we should be searching for other occurence of `ToLocale().c_str()` in the codebase as this could lead to similar, hard to catch, bugs?

**Comment by victorlevasseur** [comment]
When these temporary are directly given to a function/method, this is safe. On the contrary, when the ```char*``` pointer is stored before being used, this could lead to some unpredicted bugs. But I think this is the only case of storing char* before use in the whole codebase.

**Comment by brylie** [comment]
Wow. Great work! :+1:
